# Image de base Java 17
FROM eclipse-temurin:17-jdk

# Répertoire de travail
WORKDIR /app

# Copier le JAR généré par Maven
COPY target/*.jar app.jar

# Port exposé par Spring Boot
EXPOSE 8080

# Lancer l'application
ENTRYPOINT ["java", "-jar", "app.jar"]
